title: Hello, I'm Zephyr006.
description: > # this means to ignore newlines until "baseurl:"
  Zephyrus的个人主页. Zephyr006的个人主页.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog


theme: jekyll-theme-leap-day

# Tracker
analytics: # Google Analytics
baidu-analytics: b4761476287fea924071c3ecae0bb04c

# visitors count and comments
leancloud:
  visitors_count_enable: true
  valine_enable: true
  app_id: uVxBr36Ym96YfMR8D4zM6W4K-gzGzoHsz
  app_key: 2hPyUvz8kUp1UvgABujAb9M5

paginate: 8

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
