theme: jekyll-theme-leap-day


title: Welcome to Zephyr's world.
description: > # this means to ignore newlines until "baseurl:"
  Zephyrus的个人主页. Zephyr006的个人主页.
permalink: ':title/'
url: "https://zephyr006.github.io"  # the base hostname & protocol for your site

show_downloads: false
lang: zh-CN
github:
  owner_url: https://github.com/Zephyr006
  owner_name: Zephyr006

# Tracker
google_analytics: false # Google Analytics
baidu-analytics: b4761476287fea924071c3ecae0bb04c

# visitors count and comments
leancloud:
  visitors_count_enable: true
  valine_enable: true
  app_id: uVxBr36Ym96YfMR8D4zM6W4K-gzGzoHsz
  app_key: 2hPyUvz8kUp1UvgABujAb9M5

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]