title: Hello, I'm Zephyr006.
description: > # this means to ignore newlines until "baseurl:"
  Zephyrus的个人主页. Zephyr006的个人主页.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zephyr006.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zephyr006 # add your name
author-img: Zephyr006.jpg # add your photo
about-author: 一个不断学习的佛系青年. # add description
social-twitter: https://www.cnblogs.com/wang1024 # add your Twitter handle
social-facebook: https://me.csdn.net/weixin_44204615 # add your Facebook handle
social-linkedin: https://www.jianshu.com/u/baf4da096fc5 # add your Linkedin handle
social-github: Zephyr006 # add your Github handle
social-email: wangxiansen512@163.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics
baidu-analytics: b4761476287fea924071c3ecae0bb04c

# Build Settings
markdown: kramdown
kramdown:
#  input: GFM
#  extensions:
#    - autolink
#    - footnotes
#    - smart
#  use_coderay: true
#  syntax_highlighter: rouge
#  coderay:
#    coderay_line_numbers:  nil
  toc_levels: 3
  auto_id_stripping: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-toc

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
